texturetotx:
  thumbnail: "textureBakeSet.svg"
  label: "Text to tx"
  steps:
    texturetotx:
      index: 50
      commands:
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
          parameters:
            skip_existing_conformed_file: false
            included_extensions: 
              - .tiff
              - .png
              - .jpeg
              - .jpg
              - .exr
              - .tga
            excluded_extensions:
              - .ma
        texturetotx:
          path: "texturetotx.commands.texturetotx.TextureToTx"
          ask_user: True
          parameters:
            file_paths:
              value: !command-output "texturetotx:get_references"
              hide: true
